version: "3.9"

services:

  redis:
    image: redis:7-alpine
    restart: unless-stopped

    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru

    volumes:
      - redis_data:/data

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - disasetu-network


  backend:
    build: .

    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "8000:8000"

    networks:
      - disasetu-network


volumes:
  redis_data:

networks:
  disasetu-network:
    driver: bridge