from fastapi import APIRouter, File, UploadFile, HTTPException, Depends, status
import cloudinary
import cloudinary.uploader
import os
from sqlalchemy.orm import Session
from app.core.config import settings
from app.core.database import get_db
from app.core.security import get_current_student
from app.schemas.student import StudentProfileUpdate, StudentProfileResponse
from app.models.user import Student

router = APIRouter()

# Setup cloudinary configuration
try:
    if settings.CLOUDINARY_API_SECRET in ("<your_api_secret>", ""):
        print("WARNING: Cloudinary API secret is not set correctly in your .env file!")
        
    cloudinary.config( 
        cloud_name = settings.CLOUDINARY_CLOUD_NAME, 
        api_key = settings.CLOUDINARY_API_KEY, 
        api_secret = settings.CLOUDINARY_API_SECRET,
        secure=True
    )
except Exception as e:
    print(f"Error configuring cloudinary: {e}")

@router.post("/upload-resume")
async def upload_resume(resume: UploadFile = File(...)):
    """
    Endpoint for uploading a student resume to cloudinary.
    """
    if not resume:
        raise HTTPException(status_code=400, detail="No file provided")
        
    try:
        # File object generated by FastAPI can be directly read
        content = await resume.read()
        
        # Uploading to cloudinary
        upload_result = cloudinary.uploader.upload(
            content,
            resource_type="auto", # auto detect if it is pdf or docx, etc.
            folder="student_resumes" 
        )
        
        # In a real app, you would save upload_result["secure_url"] into the database associated with the user.
        return {
            "message": "Resume uploaded successfully",
            "url": upload_result.get("secure_url"),
            "public_id": upload_result.get("public_id"),
            "format": upload_result.get("format")
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.get("/profile", response_model=StudentProfileResponse)
async def get_student_profile(
    current_user: dict = Depends(get_current_student),
    db: Session = Depends(get_db)
):
    """
    Get the current student's profile from the database.
    """
    student = db.query(Student).filter(Student.id == current_user["user_id"]).first()
    if not student:
        raise HTTPException(status_code=404, detail="Student profile not found")
    return student

@router.patch("/profile", response_model=StudentProfileResponse)
async def update_student_profile(
    profile_data: StudentProfileUpdate,
    current_user: dict = Depends(get_current_student),
    db: Session = Depends(get_db)
):
    """
    Update the current student's profile.
    """
    student = db.query(Student).filter(Student.id == current_user["user_id"]).first()
    if not student:
        raise HTTPException(status_code=404, detail="Student profile not found")
    
    update_data = profile_data.model_dump(exclude_unset=True)
    for key, value in update_data.items():
        setattr(student, key, value)
    
    db.commit()
    db.refresh(student)
    return student
