from fastapi import APIRouter, File, UploadFile, HTTPException
import cloudinary
import cloudinary.uploader
import os
from app.core.config import settings

router = APIRouter()

# Setup cloudinary configuration
try:
    if settings.CLOUDINARY_API_SECRET in ("<your_api_secret>", ""):
        print("WARNING: Cloudinary API secret is not set correctly in your .env file!")
        
    cloudinary.config( 
        cloud_name = settings.CLOUDINARY_CLOUD_NAME, 
        api_key = settings.CLOUDINARY_API_KEY, 
        api_secret = settings.CLOUDINARY_API_SECRET,
        secure=True
    )
except Exception as e:
    print(f"Error configuring cloudinary: {e}")

@router.post("/upload-resume")
async def upload_resume(resume: UploadFile = File(...)):
    """
    Endpoint for uploading a student resume to cloudinary.
    """
    if not resume:
        raise HTTPException(status_code=400, detail="No file provided")
        
    try:
        # File object generated by FastAPI can be directly read
        content = await resume.read()
        
        # Uploading to cloudinary
        upload_result = cloudinary.uploader.upload(
            content,
            resource_type="auto", # auto detect if it is pdf or docx, etc.
            folder="student_resumes" 
        )
        
        # In a real app, you would save upload_result["secure_url"] into the database associated with the user.
        return {
            "message": "Resume uploaded successfully",
            "url": upload_result.get("secure_url"),
            "public_id": upload_result.get("public_id"),
            "format": upload_result.get("format")
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
