from fastapi import APIRouter, File, UploadFile, HTTPException, Depends, status
import cloudinary
import cloudinary.uploader
import os
import json
import uuid
import redis
from sqlalchemy.orm import Session
from app.core.config import settings
from app.core.database import get_db
from app.core.security import get_current_student
from app.schemas.student import StudentProfileUpdate, StudentProfileResponse, StudentEducation
from app.models.user import Student

router = APIRouter()

RESUME_QUEUE_KEY = "resume_parse_queue"
JOB_STATUS_KEY_PREFIX = "resume_job:"
STUDENT_LAST_JOB_KEY_PREFIX = "student_last_resume_job:"


def _get_redis_client() -> redis.Redis:
    return redis.Redis.from_url(settings.REDIS_URL, decode_responses=True)


def _normalize_education(entries):
    normalized = []
    if not entries:
        return normalized
    for entry in entries:
        if not isinstance(entry, dict):
            continue
        if not entry.get("id"):
            entry["id"] = str(uuid.uuid4())
        normalized.append(entry)
    return normalized

# Setup cloudinary configuration
try:
    if settings.CLOUDINARY_API_SECRET in ("<your_api_secret>", ""):
        print("WARNING: Cloudinary API secret is not set correctly in your .env file!")
        
    cloudinary.config( 
        cloud_name = settings.CLOUDINARY_CLOUD_NAME, 
        api_key = settings.CLOUDINARY_API_KEY, 
        api_secret = settings.CLOUDINARY_API_SECRET,
        secure=True
    )
except Exception as e:
    print(f"Error configuring cloudinary: {e}")

@router.post("/upload-resume")
async def upload_resume(
    resume: UploadFile = File(...),
    current_user: dict = Depends(get_current_student),
    db: Session = Depends(get_db)
):
    """
    Endpoint for uploading a student resume to cloudinary.
    Requires authentication (student JWT token).
    """
    if not resume:
        raise HTTPException(status_code=400, detail="No file provided")

    filename = (resume.filename or "").lower()
    content_type = (resume.content_type or "").lower()
    if not (filename.endswith(".pdf") or content_type == "application/pdf"):
        raise HTTPException(status_code=400, detail="Only PDF resumes are supported")
        
    try:
        # File object generated by FastAPI can be directly read
        content = await resume.read()
        
        # Uploading to cloudinary
        upload_result = cloudinary.uploader.upload(
            content,
            resource_type="auto", # auto detect if it is pdf or docx, etc.
            folder="student_resumes" 
        )
        
        secure_url = upload_result.get("secure_url")

        # Persist the resume URL to the student's profile
        if secure_url:
            try:
                student_id = uuid.UUID(str(current_user["user_id"]))
            except Exception:
                raise HTTPException(status_code=401, detail="Invalid token subject")

            student = db.query(Student).filter(Student.id == student_id).first()
            if student:
                student.resume_url = secure_url
                db.commit()

        # Enqueue background parsing + embedding job in Redis
        job_id = str(uuid.uuid4())
        payload = {
            "job_id": job_id,
            "student_id": str(current_user["user_id"]),
            "resume_url": secure_url,
        }

        try:
            redis_client = _get_redis_client()
            redis_client.rpush(RESUME_QUEUE_KEY, json.dumps(payload))
            redis_client.hset(
                f"{JOB_STATUS_KEY_PREFIX}{job_id}",
                mapping={
                    "status": "queued",
                    "student_id": payload["student_id"],
                    "resume_url": secure_url or "",
                },
            )
            redis_client.expire(f"{JOB_STATUS_KEY_PREFIX}{job_id}", 60 * 60)
            redis_client.setex(
                f"{STUDENT_LAST_JOB_KEY_PREFIX}{payload['student_id']}",
                60 * 60,
                job_id,
            )
        except Exception:
            # Upload succeeded; job enqueue failure should not break resume_url persistence.
            job_id = ""

        return {
            "message": "Resume uploaded successfully",
            "url": secure_url,
            "public_id": upload_result.get("public_id"),
            "format": upload_result.get("format"),
            "job_id": job_id,
            "job_status": "queued" if job_id else "enqueue_failed",
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/resume-job-status")
async def get_resume_job_status(
    current_user: dict = Depends(get_current_student),
):
    """Return latest resume parse job status for current student (stored in Redis)."""

    student_id = str(current_user["user_id"])
    try:
        redis_client = _get_redis_client()
        job_id = redis_client.get(f"{STUDENT_LAST_JOB_KEY_PREFIX}{student_id}")
        if not job_id:
            return {"status": "none"}

        status_data = redis_client.hgetall(f"{JOB_STATUS_KEY_PREFIX}{job_id}")
        # If the key expired, still return job_id for debugging.
        return {
            "job_id": job_id,
            "status": status_data.get("status", "unknown"),
            "error": status_data.get("error", ""),
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.get("/profile", response_model=StudentProfileResponse)
async def get_student_profile(
    current_user: dict = Depends(get_current_student),
    db: Session = Depends(get_db)
):
    """
    Get the current student's profile from the database.
    """
    student = db.query(Student).filter(Student.id == current_user["user_id"]).first()
    if not student:
        raise HTTPException(status_code=404, detail="Student profile not found")
    return student

@router.patch("/profile", response_model=StudentProfileResponse)
async def update_student_profile(
    profile_data: StudentProfileUpdate,
    current_user: dict = Depends(get_current_student),
    db: Session = Depends(get_db)
):
    """
    Update the current student's profile.
    """
    student = db.query(Student).filter(Student.id == current_user["user_id"]).first()
    if not student:
        raise HTTPException(status_code=404, detail="Student profile not found")
    
    update_data = profile_data.model_dump(exclude_unset=True)
    if "education" in update_data:
        update_data["education"] = _normalize_education(update_data.get("education"))
    for key, value in update_data.items():
        setattr(student, key, value)
    
    db.commit()
    db.refresh(student)
    return student


@router.get("/education", response_model=list[StudentEducation])
async def get_education(
    current_user: dict = Depends(get_current_student),
    db: Session = Depends(get_db),
):
    student = db.query(Student).filter(Student.id == current_user["user_id"]).first()
    if not student:
        raise HTTPException(status_code=404, detail="Student profile not found")
    return student.education or []


@router.post("/education", response_model=StudentEducation, status_code=status.HTTP_201_CREATED)
async def add_education(
    education_entry: StudentEducation,
    current_user: dict = Depends(get_current_student),
    db: Session = Depends(get_db),
):
    student = db.query(Student).filter(Student.id == current_user["user_id"]).first()
    if not student:
        raise HTTPException(status_code=404, detail="Student profile not found")

    entry = education_entry.model_dump()
    entry["id"] = str(uuid.uuid4())
    entries = list(student.education or [])
    entries.append(entry)
    student.education = entries
    db.commit()
    db.refresh(student)
    return entry


@router.patch("/education/{education_id}", response_model=StudentEducation)
async def update_education(
    education_id: str,
    education_entry: StudentEducation,
    current_user: dict = Depends(get_current_student),
    db: Session = Depends(get_db),
):
    student = db.query(Student).filter(Student.id == current_user["user_id"]).first()
    if not student:
        raise HTTPException(status_code=404, detail="Student profile not found")

    entries = list(student.education or [])
    idx = next((i for i, e in enumerate(entries) if str(e.get("id")) == education_id), None)
    if idx is None:
        raise HTTPException(status_code=404, detail="Education entry not found")

    updated = education_entry.model_dump()
    updated["id"] = education_id
    entries[idx] = updated
    student.education = entries
    db.commit()
    db.refresh(student)
    return updated


@router.delete("/education/{education_id}")
async def delete_education(
    education_id: str,
    current_user: dict = Depends(get_current_student),
    db: Session = Depends(get_db),
):
    student = db.query(Student).filter(Student.id == current_user["user_id"]).first()
    if not student:
        raise HTTPException(status_code=404, detail="Student profile not found")

    entries = list(student.education or [])
    next_entries = [e for e in entries if str(e.get("id")) != education_id]
    if len(next_entries) == len(entries):
        raise HTTPException(status_code=404, detail="Education entry not found")

    student.education = next_entries
    db.commit()
    return {"message": "Education entry deleted"}
